#!/usr/bin/env bash
#fizzbuzz multiplos

for ((i=1; i<101; i++))
do
	if [ $i % 3 ] && [ $i % 5 ]; then
	       echo "FizzBuzz"
       elif [ $i % 3 ]; then
		echo "Fizz"
       elif [ $i % 5 ]; then
		echo "Buzz"
 	else		
		echo "$i"
	fi
done
