#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times an 
#9 line Hi

i=10

while [ $i -gt 0 ]
do
if [ $i = 2 ]
then
    echo "Hi"
else
    echo "Holberton School"
fi
    i=$((i - 1))
done
