#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times an hi in 9

i=1
while [ $i -le 10 ]
do
    echo "Holberton School"
    if [ "$i" -eq 9 ]
    then
	echo "Hi"
    fi

    ((i++))
done
