#!/usr/bin/env bash
#killing it with ctrl+c


trap "sudo rm -f /var/run/codingschoolscript.pid; exit" SIGQUIT
trap "sudo rm -f /var/run/codingschoolscript.pid; echo I hate the kill command; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 2
done	
