#!/usr/bin/env bash
#manage_my_process, manage_my_process

#bash script to manage 'manage_my_process'
if [ "$1" == "start" ]; then
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process started"
