#!/usr/bin/env bash
#manage_my_process, manage_my_process

filepid="/var/run/my_process.pid"

start() {
	
	./manage_my_process &
	echo "$!" > "$filepid"
}
stop() {
	
	sudo kill -15 "$(cat "$filepid")" && rm -f "$filepid"
}

case "$1" in 
	
start ) start	
       	echo "manage_my_process started"
	 ;;

 stop ) stop
	 echo "manage_my_process stopped"
	;;

restart ) stop; start 
	echo "manage_my_process restarted"
	;;

*) echo "Usage: manage_my_process {start|stop|restart}"

esac
